apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: helloworld-go
  name: helloworld-go
  namespace: default
spec:
  selector:
    matchLabels:
      app: helloworld-go
      version: latest
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: helloworld-go
        version: latest
    spec:
      containers:
        - image: docker.pkg.github.com/dduzgun-security/helloworld-go/image:latest
          name: helloworld-go
          imagePullPolicy: Always
          resources:
            limits:
              cpu: "0.5"
              memory: "30Mi"
          ports:
            - containerPort: 8080
              name: http
          env:
            - name: ENVIRONMENT
              value: test
      imagePullSecrets:
      - name: regcred
